name: AIKU-project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2023.5.7=h56e8100_0
  - certifi=2023.5.7=py38haa95532_0
  - cffi=1.15.1=py38h2bbff1b_3
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.1=py38h21b164f_0
  - cuda-cccl=12.1.109=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - idna=3.4=py38haa95532_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.4.0=py38haa244fe_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=py38haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py38haa244fe_0
  - lerc=3.0=hd77b12b_0
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.2.106=0
  - libcurand-dev=10.3.2.106=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_0
  - libfaiss=1.7.4=h2e52968_0_cpu
  - libffi=3.4.4=hd77b12b_0
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h8bd8f75_46356
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.6=py38hf11a4ad_1
  - mkl_random=1.2.2=py38hf11a4ad_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openssl=1.1.1u=h2bbff1b_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.0.1=py38haa95532_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.16=h6244533_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=2.0.1=py3.8_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-mutex=1.0=cuda
  - pywin32=305=py38h2bbff1b_0
  - pyzmq=25.0.2=py38hd77b12b_0
  - setuptools=66.0.0=py38haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.2=py38h294d835_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.6.2=pyha770c72_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - blis==0.7.9
    - catalogue==2.0.8
    - chardet==5.1.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - coloredlogs==15.0.1
    - confection==0.0.4
    - contourpy==1.0.7
    - cycler==0.11.0
    - cymem==2.0.7
    - cython==0.29.34
    - datasets==2.13.1
    - dill==0.3.6
    - faiss==1.7.4
    - faiss-cpu==1.7.4
    - filelock==3.12.0
    - flatbuffers==23.5.9
    - fonttools==4.39.4
    - frozenlist==1.3.3
    - fsspec==2023.5.0
    - huggingface-hub==0.14.1
    - humanfriendly==10.0
    - importlib-resources==5.12.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - lightgbm==3.3.5
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - murmurhash==1.0.9
    - networkx==3.1
    - nltk==3.8.1
    - nmslib==2.1.1
    - onnxruntime==1.14.1
    - pandas==2.0.1
    - pathy==0.10.1
    - pillow==9.5.0
    - preshed==3.0.8
    - protobuf==4.23.0
    - psutil==5.9.5
    - pyarrow==12.0.1
    - pybind11==2.6.1
    - pydantic==1.10.7
    - pyjnius==1.5.0
    - pyparsing==3.0.9
    - pypdf2==3.0.1
    - pyreadline3==3.4.1
    - pyserini==0.21.0
    - pytz==2023.3
    - pyyaml==6.0
    - regex==2023.5.5
    - requests==2.30.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.99
    - smart-open==6.3.0
    - spacy==3.5.3
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.6
    - sympy==1.12
    - thinc==8.1.10
    - threadpoolctl==3.1.0
    - tokenizers==0.13.3
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - tqdm==4.65.0
    - transformers==4.29.1
    - typer==0.7.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - urllib3==2.0.2
    - wasabi==1.1.1
    - xxhash==3.2.0
    - yarl==1.9.2
